# Generated by Django 5.2.4 on 2025-07-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0004_order_guest_email_order_guest_name_order_guest_phone_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="guest_email",
        ),
        migrations.RemoveField(
            model_name="order",
            name="guest_name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="guest_phone",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_address",
        ),
    ]
